/// DO NOT EDIT THIS FILE EXCEPT TO ENTER INITIAL VERSION AND OTHER META INFO 
/// THIS FILE IS AUTOMATICALLY OVER WRITTEN BY MetaUpdate 

/// @nodoc
Map<String, String> meta = <String, String>{
  "version":"1.0.0",
};
  