name: nitrite_demo
description: A simple Flutter project to demonstrate Nitrite database usage.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_slidable: ^3.0.0
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  nitrite: ^1.1.1
  nitrite_hive_adapter: ^1.1.1
  path_provider: ^2.0.15
  uuid: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.2.3
  build_runner: ^2.4.6
  custom_lint: any
  riverpod_lint: any
  nitrite_generator: ^1.1.1
  icons_launcher: ^2.1.3

flutter:
  uses-material-design: true
  assets:
   - assets/

