targets:
  $default:
    builders:
      nitrite_entity_generator:
        enabled: true

builders:
  nitrite_entity_generator:
    import: "package:nitrite_entity_generator/builder.dart"
    # The builder function name, which gets called on build/watch
    builder_factories: ["nitriteEntityBuilder"]
    # The 'partId' argument to 'PartBuilder' is 'no2'
    build_extensions: {".dart": [".no2.dart"]}
    # Apply the Builder to the package with a direct dependency on the package exposing the builder
    auto_apply: dependents
    build_to: source
    # To copy the '.no2.dart' content into '.no2.dart' in the source tree
    # Combine the output of multiple builders into one output (combining_builder)
    applies_builders: ["source_gen|combining_builder"]