name: nitrite_entity_generator
description: Nitrite entity generator
version: 0.0.1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  build: ^2.3.0
  build_config: ^1.0.0
  code_builder: ^4.1.0
  dart_style: ^2.2.3
  source_gen: ^1.4.0
  analyzer: ^5.12.0
  nitrite: ^0.0.1

dev_dependencies:
  build_test: ^2.1.5
  build_runner: ^2.3.3
  test: ^1.21.1