name: nitrite_entity_generator
description: Nitrite entity generator. Automatically generates Nitrite entities from Dart classes.
version: 1.0.0
homepage: https://nitrite.dizitart.com/
repository: https://github.com/nitrite/nitrite-flutter

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  build: ^2.3.0
  build_config: ^1.0.0
  code_builder: ^4.1.0
  dart_style: ^2.2.3
  source_gen: ^1.4.0
  analyzer: ^5.12.0
  nitrite: ^1.0.0
  collection: ^1.17.1

dev_dependencies:
  build_test: ^2.1.5
  build_runner: ^2.3.3
  test: ^1.21.1
  lints: ^2.1.1

funding:
  - https://github.com/sponsors/anidotnet