name: nitrite_entity_generator
description: Nitrite entity generator
version: 0.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  build: ^2.3.0
  build_config: ^1.0.0
  code_builder: ^4.1.0
  dart_style: ^2.2.3
  source_gen: ^1.2.2
  analyzer: ^4.3.1
  nitrite: ^0.0.1

dev_dependencies:
  build_test: ^2.1.5
  build_runner: any
  test: ^1.21.1

dependency_overrides:
  nitrite:
    path: ../nitrite