name: Nitrite
repository: https://github.com/nitrite/nitrite-flutter

packages:
  - packages/**
  - examples/**
  - doc/**

ignore:
  - packages/**/build/**
  - examples/**/build/**

command:
  version:
    # Generate commit links in package changelogs.
    linkToCommits: true
    # Only allow versioning to happen on main branch.
    branch: main
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: true

scripts:
  prepare:
    run: |
      dart pub global activate coverage &&
      dart pub global activate coverde &&
      dart pub global activate dartdoc
    description: Prepare build system.

  generate:
    run: |
      melos exec -- dart run build_runner build --delete-conflicting-outputs
    description: Run `build_runner` for all package.

  lint:all:
    run: melos run analyze && melos run format
    description: Run all static analysis checks.

  analyze:
    run: |
      melos exec -c 10 -- flutter analyze --fatal-infos
    description: Run `flutter analyze` for all packages.

  format:
    run: melos exec dart format . --fix
    description: Run `dart format` for all packages.

  dartdoc:
    run: melos exec dart doc .
    description: Run dartdoc checks for all packages.

  test:
    run: |
      melos run test-with-coverage --no-select
    description: |
      Run all tests available.

  test-with-coverage:
    run: |
      melos run generate &&
      melos exec -c 6 --fail-fast --ignore="*generator*" --ignore="*demo*" -- flutter test --coverage --no-pub &&
      melos exec -c 6 --fail-fast --scope="*generator*" -- dart pub global run coverage:test_with_coverage &&
      melos exec --ignore="*demo*" -- genhtml coverage/lcov.info --output-directory=coverage/ &&
      melos exec -c 1 --file-exists=coverage/lcov.info -- coverde filter --input ./coverage/lcov.info --output MELOS_ROOT_PATH/coverage/filtered.lcov.info --filters \.g\.dart
      coverde value -i coverage/filtered.lcov.info > MELOS_ROOT_PATH/coverage/result.txt
    description: Run `flutter test` for a specific package.

  clean:deep:
      run: git clean -x -d -f -q
      description: Clean things very deeply, can be used to establish "pristine checkout" status.

