name: nitrite_flutter

environment:
  sdk: '>=2.19.0 <3.0.0'
dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.4.0
  melos: ^3.0.1
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
dependencies:
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1

