name: nitrite
description: An embedded nosql document store for dart/flutter. It supports both in-memory and file based persistent store.
version: 1.0.3
homepage: https://nitrite.dizitart.com/
repository: https://github.com/nitrite/nitrite-flutter

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  logging: ^1.2.0
  dart_numerics: ^0.0.6
  rxdart: ^0.27.7
  event_bus: ^2.0.0
  quiver: ^3.1.0
  crypt: ^4.2.1
  collection: ^1.17.1
  uuid: ^4.2.0
  meta: ^1.10.0

dev_dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.3.3
  nitrite_generator: ^1.0.3
  mockito: ^5.2.0
  test: ^1.24.6
  faker: ^2.0.0
  yaml: ^3.1.1

flutter:
  assets:
    - pubspec.yaml

funding:
  - https://github.com/sponsors/anidotnet