name: nitrite
description: An embedded nosql document store for dart/flutter.
version: 0.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
   uuid: 3.0.6
   logging: ^1.0.2
   mutex: ^3.0.0
   collection: ^1.16.0
   json_annotation: ^4.5.0
   dart_numerics: ^0.0.6
   string_splitter: ^1.0.0+1
   rxdart: ^0.27.4
   event_bus: ^2.0.0
   quiver: ^3.1.0
   yaml: ^3.1.1
   cryptography: ^2.0.5
   build: any
   source_gen: any
   analyzer: ^4.3.1
   meta: ^1.8.0
   faker: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.1.7
  nitrite_entity_generator:
    path: ../nitrite_entity_generator
  mockito: ^5.2.0

