name: nitrite
description: An embedded nosql document store for dart/flutter.
version: 0.0.1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.2
  dart_numerics: ^0.0.6
  rxdart: ^0.27.4
  event_bus: ^2.0.0
  quiver: ^3.1.0
  crypt: ^4.2.1
  collection: ^1.16.0
  uuid: ^3.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  nitrite_entity_generator: ^0.0.1
  mockito: ^5.2.0
  encrypt: ^5.0.1
  test: ^1.16.0
  faker: ^2.0.0
  yaml: ^3.1.1

flutter:
  uses-material-design: true
  assets:
    - pubspec.yaml