name: nitrite
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
   uuid: 3.0.6
   logging: ^1.0.2
   mutex: ^3.0.0
   collection: ^1.16.0
   json_annotation: ^4.5.0
   dart_numerics: ^0.0.6
   string_splitter: ^1.0.0+1
   rxdart: ^0.27.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.1.11
  json_serializable: ^6.2.0

