name: nitrite_generator
description: Nitrite entity generator. Automatically generates Nitrite entities from Dart classes.
version: 1.1.0
homepage: https://nitrite.dizitart.com/
repository: https://github.com/nitrite/nitrite-flutter

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  build: ^2.3.0
  build_config: ^1.0.0
  code_builder: ^4.9.0
  dart_style: ^2.3.4
  source_gen: ^1.5.0
  analyzer: ^6.2.0
  nitrite: ^1.1.0
  collection: ^1.17.1

dev_dependencies:
  build_test: ^2.2.2
  build_runner: ^2.4.7
  test: ^1.25.0
  lints: ">=3.0.0 <5.0.0"

funding:
  - https://github.com/sponsors/anidotnet