name: nitrite_spatial
description: Spatial extension for Nitrite database.
version: 1.0.0
homepage: https://nitrite.dizitart.com/
repository: https://github.com/nitrite/nitrite-flutter

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dart_jts: ^0.3.0+1
  nitrite: ^1.0.0

dev_dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7

flutter:
  assets:
    - pubspec.yaml

funding:
  - https://github.com/sponsors/anidotnet

