import 'dart:io';

import 'package:test/test.dart';
import 'package:yaml/yaml.dart';

/// Stamps the package version into the source tree.
///
/// It reads `pubspec.yaml` off disk rather than through Flutter's `rootBundle`, which is what
/// it used to do. `rootBundle` needs `WidgetsFlutterBinding`, so this file pulled in
/// `package:flutter` and could only be compiled by `flutter test` - under `dart test` it
/// crashed the Dart front end in the FFI transformer before running anything. Nothing here
/// wants a widget binding: the pubspec is a file in the package root and `dart:io` was already
/// imported to write the output beside it.
void main() {
  group(retry: 3, 'Meta Writer', () {
    test('Write Meta', () async {
      final fileContent = await File('pubspec.yaml').readAsString();
      final pubspec = loadYaml(fileContent);
      var version = pubspec['version'];

      String metaDartFileContents = """
/// DO NOT EDIT THIS FILE EXCEPT TO ENTER INITIAL VERSION AND OTHER META INFO
/// THIS FILE IS AUTOMATICALLY OVER WRITTEN BY MetaUpdate
Map<String, String> meta = <String, String>{
  "version": "$version",
};
""";

      var metaDartFile = File('lib/src/store/memory/in_memory_meta.dart');
      await metaDartFile.writeAsString(metaDartFileContents, flush: true);
    });
  });
}
