name: nitrite_support
description: Support library for Nitrite database.
version: 1.0.0
homepage: https://nitrite.dizitart.com/
repository: https://github.com/nitrite/nitrite-flutter

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  path: ^1.8.0
  nitrite: ^1.0.0
  compute: ^1.0.2
  convert: ^3.1.1
  encrypt: ^5.0.1

dev_dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.16.0
  faker: ^2.0.0
  nitrite_hive_adapter: ^1.0.0
  collection: ^1.16.0
  build_runner: ^2.3.3
  nitrite_generator: ^1.0.0

funding:
  - https://github.com/sponsors/anidotnet