name: nitrite_hive_adapter
description: A persistent storage module for Nitrite database based on Hive.
version: 1.1.1
homepage: https://nitrite.dizitart.com/
repository: https://github.com/nitrite/nitrite-flutter

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  hive: ^2.2.3
  path: ^1.8.3
  nitrite: ^1.1.0
  path_provider: ^2.1.1
  logging: ^1.0.2
  meta: ^1.10.0

dev_dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ">=3.0.1 <5.0.0"
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  nitrite_generator: ^1.1.1
  test: any
  encrypt: ^5.0.3
  faker: ^2.0.0
  yaml: ^3.1.1
  uuid: ^4.2.0
  collection: ^1.16.0

flutter:
  assets:
    - pubspec.yaml

funding:
  - https://github.com/sponsors/anidotnet