name: Build Nitrite

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "README.md"

jobs:
  test_linux:
    name: Build Nitrite on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install lcov
        run: sudo apt-get update -qq -y && sudo apt-get install lcov

      - name: Setup Build System
        shell: bash
        run: .\.github\workflows\scripts\install-tools.sh

      - name: Build Nitrite
        run: melos run test

      - name: Upload coverage
        if: github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          name: codecov-umbrella
          files: ./coverage/filtered.lcov.info

  test_macos:
    name: Build Nitrite on MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install lcov
        run: brew install lcov

      - name: Setup Build System
        shell: bash
        run: .\.github\workflows\scripts\install-tools.sh

      - name: Build Nitrite
        run: melos run test

  test_windows:
    name: Build Nitrite on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install lcov
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install lcov

      - name: Setup Build System
        shell: cmd
        run: .\.github\workflows\scripts\install-tools.bat

      - name: Build Nitrite
        shell: cmd
        working-directory: ${GITHUB_WORKSPACE}
        run: melos run test
