name: Validate Nitrite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_linux:
    name: Validate Nitrite on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Melos
        uses: bluefireteam/melos-action@v1

      - name: Install lcov
        run: sudo apt-get update -qq -y && sudo apt-get install lcov

      - name: Validate Nitrite
        run: melos run test:all

  test_macos:
    name: Validate Nitrite on MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Melos
        uses: bluefireteam/melos-action@v1

      - name: Install lcov
        run: brew install lcov

      - name: Validate Nitrite
        run: melos run test:all

  test_windows:
    name: Validate Nitrite on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Melos
        uses: bluefireteam/melos-action@v1

      - name: Install lcov
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          name: install lcov

      - name: Validate Nitrite
        shell: cmd
        run: melos run test:all
