name: Release Nitrite Hive Adapter

on:
  push:
    tags:
      - 'nitrite_hive_adapter-[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    name: Publish on pub.dev
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Required for authentication using OIDC
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          channel: 'stable'

      # This action adds a token needed for pub.dev authentication
      - name: Install Dart
        uses: dart-lang/setup-dart@v1.7.0
        with:
          sdk: stable

      - name: Setup Build System
        shell: bash
        run: |
          chmod +x ./.github/workflows/scripts/install-tools.sh
          ./.github/workflows/scripts/install-tools.sh

      - name: Generate Code
        run: melos run generate

      - name: Format Nitrite
        run: melos run lint:all

      - name: Publish Nitrite Hive Adapter
        uses: nick-fields/retry@v3
        with:
          max_attempts: 10
          timeout_minutes: 60
          command: |
            cd packages/nitrite_hive_adapter
            flutter pub publish --force