name: Release Nitrite

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    name: Publish Nitrite to pub.dev
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Build System
        shell: bash
        run: |
          chmod +x ./.github/workflows/scripts/install-tools.sh
          ./.github/workflows/scripts/install-tools.sh

      - name: Build Nitrite
        run: melos run test

      - name: Generate Docs
        run: melos run dartdoc

      - name: Publish Nitrite
        run: melos run publish
        with:
          environment: dizitart